name: Publish cbxy-generator

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    defaults:
      run:
        working-directory: cbxy-generator

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Publish to PyPI
        run: uv publish
